language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 static_checking.c -o hello
  - ./hello
  - gcov static_checking.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
